name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            .
            fuzz
      - run: cargo test
      - run: cargo install cargo-fuzz --locked
      - run: make fuzz FUZZ_SECONDS=20
